Changed mounting/unmounting of an FSspec

diff --git a/trunk/share/pentoo-installer/partition_finalise b/trunk/share/pentoo-installer/partition_finalise
--- a/trunk/share/pentoo-installer/partition_finalise
+++ b/trunk/share/pentoo-installer/partition_finalise
@@ -23,37 +23,20 @@ source "${SHAREDIR}"/partition_common.sh || exit $?
 #########################################
 ## START: dialog functions/definitions ##
 
-# partition_encryptswap()
-# sets up an encrypted swap partition
-# 
-# parameters (required)
-#  _PARTITION: The partition to encrypt
-#  _CRYPTNAME: Name used for cryptsetup
-#
-# returns 0 on success
-# anything else is a real error
-#
-partition_encryptswap() {
-	# check input
-	check_num_args "${FUNCNAME}" 2 $# || return $?
-	cryptsetup create -c aes-xts-plain64:sha512 -s 512 -d /dev/urandom "${2}" "${1}" >>"${LOG}" 2>&1 \
-		|| return $?
-}
-
-# partition_luks_setup()
+# partition_crypt_setup()
 # Generate a key, optionnaly encrypt it with gpg
-# format a luks partition. Cipher and hash chosen arbitrarily
+# format a luks or swap partition. Cipher and hash chosen arbitrarily
 # uses cryptsetup
 # writes the key to STDOUT, in base64 form for gpg
 # 
 # parameters (required)
 #  _PARTITION: The partition to encrypt
 #  _CRYPTNAME: name used by cryptsetup
-#  _CRYPTTYPE: gpg or ''
+#  _CRYPTTYPE: swap, gpg or ''
 #
 # return !=0 on failure (including user abort with ERROR_CANCEL=64)
 #
-partition_luks_setup() {
+partition_crypt_setup() {
 	# check input
 	check_num_args "${FUNCNAME}" 3 $# || return $?
 	local _PARTITION="${1}"
@@ -62,6 +45,16 @@ partition_luks_setup() {
 	# use uuid as temp file name
 	local _UUID="$(uuidgen)" || return $?
 	case "${_CRYPTTYPE}" in
+		swap)
+			# TODO swap key is shorter then before with -d /dev/urandom and
+			# Maximum keyfile size: 8192kB
+			head -c60 /dev/urandom | base64 | head -n1 | tr -d '\n' > /tmp/"${_UUID}" || return $?
+			cryptsetup -c aes-xts-plain64:sha512 -s 512 -d /tmp/"${_UUID}" open --type plain "${_PARTITION}" "${_CRYPTNAME}" || return $?
+			# print to STDOUT
+			cat /tmp/"${_UUID}" || return $?
+			# clean up
+			rm /tmp/"${_UUID}" || return $?
+			;;
 		gpg)
 			show_dialog --msgbox "We will now generate a GPG-encrypted luks key for ${_PARTITION}" 0 0 || return $?
 			head -c60 /dev/urandom | base64 | head -n1 | tr -d '\n' > /tmp/"${_UUID}" || return $?
@@ -71,7 +64,7 @@ partition_luks_setup() {
 			gpg --decrypt /tmp/"${_UUID}".asc | cryptsetup -h sha512 -c aes-xts-plain64 -s 512 luksFormat --align-payload=8192 "${_PARTITION}" || return $?
 			# TODO, is this needed? Seems not
 			# show_dialog --msgbox "Please enter the GPG key for ${_PARTITION} (last time :-)" 0 0 || return $?
-			gpg --decrypt /tmp/"${_UUID}".asc | cryptsetup luksOpen "${_PARTITION}" "${_CRYPTNAME}" || return $?
+			gpg --decrypt /tmp/"${_UUID}".asc | cryptsetup open --type luks "${_PARTITION}" "${_CRYPTNAME}" || return $?
 			# print to STDOUT
 			cat /tmp/"${_UUID}".asc | base64 -w0 || return $?
 			# clean up
@@ -81,7 +74,7 @@ partition_luks_setup() {
 		'')
 			head -c60 /dev/urandom | base64 | head -n1 | tr -d '\n' > /tmp/"${_UUID}" || return $?
 			cat /tmp/"${_UUID}" | cryptsetup -h sha512 -c aes-xts-plain64 -s 512 luksFormat --align-payload=8192 "${2}" || return $?
-			cat /tmp/"${_UUID}" | cryptsetup luksOpen "${_PARTITION}" "${_CRYPTNAME}" || return $?
+			cat /tmp/"${_UUID}" | cryptsetup open --type luks "${_PARTITION}" "${_CRYPTNAME}" || return $?
 			# print to STDOUT
 			cat /tmp/"${_UUID}" || return $?
 			# clean up
@@ -105,7 +98,7 @@ partition_luks_setup() {
 check_num_args "$(basename $0)" 1 $# || exit $?
 CONFIG_LIST="${1}"
 # reverse sort by mountpoint
-CONFIG_LIST="$("${SHAREDIR}"/FSspec sort_reverse "${CONFIG_LIST}" 'mountpoint')" || exit $?
+CONFIG_LIST="$("${SHAREDIR}"/FSspec sort "${CONFIG_LIST}" 'mountpoint' 1)" || exit $?
 CONFIG_ARRAY=(${CONFIG_LIST}) || exit $?
 CONFIG_INDEX=0
 
@@ -127,17 +120,17 @@ while [ "${CONFIG_INDEX}" -lt "${#CONFIG_ARRAY[@]}" ]; do
 		CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'cryptname' "${CRYPTNAME}")" || exit $?
 		# swap partition
 		if [ "${FILESYSTEM}" = 'swap' ]; then
-			partition_encryptswap "${PARTITION}" "${CRYPTNAME}" || exit $?
+			CRYPTTYPE='swap'
 		# non-swap partition
 		else
 			if show_dialog --defaultno --yesno "Do you want to use GPG encrypted key for the partition (${PARTITION}) on (${MOUNTPOINT}) ?" 0 0; then
 				CRYPTTYPE='gpg'
-				CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'cryptname' "${CRYPTTYPE}")" || exit $?
 			fi
-			# create crypt-key and use cryptsetup
-			CRYPTKEY="$(partition_luks_setup "${PARTITION}" "${CRYPTNAME}" "${CRYPTTYPE}")" || exit $?
-			CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'cryptkey' "${CRYPTKEY}")" || exit $?
 		fi
+		CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'crypttype' "${CRYPTTYPE}")" || exit $?
+		# create crypt-key and use cryptsetup
+		CRYPTKEY="$(partition_crypt_setup "${PARTITION}" "${CRYPTNAME}" "${CRYPTTYPE}")" || exit $?
+		CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'cryptkey' "${CRYPTKEY}")" || exit $?
 		PARTPATH="/dev/mapper/${CRYPTNAME}"
 	fi
 	# format partition
@@ -160,21 +153,34 @@ while [ "${CONFIG_INDEX}" -lt "${#CONFIG_ARRAY[@]}" ]; do
 		CONFIG_ITEM="$("${SHAREDIR}"/FSspec setvalue "${CONFIG_ITEM}" 'format' "${FORMAT}")" || exit $?
 	fi
 	# mount actions
-	# TODO reuse this
-	# if [ "${FILESYSTEM}" != 'swap' ]; then
-        # # create our mount directory
-        # mkdir -p "${DESTDIR}${MOUNTPOINT}" || exit $?
-        # # mount the bad boy
-        # mount -t "${FILESYSTEM}" "${PARTPATH}" "${DESTDIR}${MOUNTPOINT}" >>"${LOG}" 2>&1
-	# else
-        # swapon ${PARTPATH} >>"${LOG}" 2>&1 || exit $?
-	# fi
+	if [ "${FILESYSTEM}" != 'swap' ]; then
+        # create our mount directory
+        mkdir -p "${DESTDIR}${MOUNTPOINT}" || exit $?
+        # mount the bad boy
+        mount -t "${FILESYSTEM}" "${PARTPATH}" "${DESTDIR}${MOUNTPOINT}" >>"${LOG}" 2>&1
+	else
+        swapon ${PARTPATH} >>"${LOG}" 2>&1 || exit $?
+	fi
 	# write FSspec back to array
 	CONFIG_ARRAY[${CONFIG_INDEX}]="${CONFIG_ITEM}" || exit $?
 	# increment array index
 	 CONFIG_INDEX="$((CONFIG_INDEX+1))" || exit $?
 done
 
+# rewrite list from array
+CONFIG_LIST="${CONFIG_ARRAY[@]}"
+# umount all again and close cryptsetup
+"${SHAREDIR}"/FSspec umountall "${CONFIG_LIST}" || exit $?
+
+# TODO this is just a test
+# echo dump start mount 1>&2
+# "${SHAREDIR}"/FSspec mountall "${CONFIG_LIST}" || exit $?
+# echo dump start umount 1>&2
+# "${SHAREDIR}"/FSspec umountall "${CONFIG_LIST}" || exit $?
+# echo dump mount/umount done 1>&2
+
+# default sort by partition again
+CONFIG_LIST="$("${SHAREDIR}"/FSspec sort "${CONFIG_LIST}" 'partition' 0)" || exit $?
 # everything ok, write new config to STDOUT
-echo -n "${CONFIG_ARRAY[@]}" || exit $?
+echo -n "${CONFIG_LIST}" || exit $?
 exit 0
