Add --config-file param

diff --git a/share/pentoo-installer/pentoo-installer b/share/pentoo-installer/pentoo-installer
--- a/share/pentoo-installer/pentoo-installer
+++ b/share/pentoo-installer/pentoo-installer
@@ -138,17 +138,29 @@ checkvm() {
 
 # INSTALLER_HEADLESS: emtpy=false
 export INSTALLER_HEADLESS=
+export INSTALLER_CONFIGFILE=
 
 # check passed arguments
 while [[ $# -gt 0 ]]; do
+  # these options require params
+  case "${1}" in
+    --config-file)
+	  if [ $# -lt 2 ] || [ "${2:0:2}" == '--' ]; then
+		  show_dialog --msgbox "ERROR: Option '${1}' requires a parameter. Aborting with  error." 0 0
+		  exit 1
+	  fi
+  esac
+  # process arguments
   case "${1}" in
     --headless)
       export INSTALLER_HEADLESS=1
-      shift
-      ;;
-    *)    # unknown option
+      shift ;;
+    --config-file)
+      export INSTALLER_CONFIGFILE="${2}"
+      shift; shift ;;
+    *) # unknown option
       show_dialog --msgbox "ERROR: Unknown option '${1}'. Aborting with  error." 0 0
-      printf "ERROR: Unknown option '${1}'. Aborting with error." 1>&2 && exit 1
+      exit 1
       ;;
   esac
 done
