stop modifying tzselect

diff --git a/share/pentoo-installer/settzclock b/share/pentoo-installer/settzclock
--- a/share/pentoo-installer/settzclock
+++ b/share/pentoo-installer/settzclock
@@ -21,7 +21,7 @@
 # reason: show_dialog() needs a way to exit "Cancel"
 
 # location of other scripts to source
-readonly SHAREDIR="$(dirname ${0})" || exit $?
+readonly SHAREDIR="$(dirname "${0}")" || exit $?
 
 # source common variables, functions and error handling
 source "${SHAREDIR}"/common.sh || exit $?
@@ -30,7 +30,7 @@ HWCLOCK_DEFAULT=utc
 TIMEZONE_DEFAULT=
 if [ -n "${INSTALLER_CONFIGFILE}" ]; then
 	# remove comments
-	CONF_FULL="$(cat "${INSTALLER_CONFIGFILE}" | jq 'del(..|.["#"]?)')" || exit $?
+	CONF_FULL="$(jq 'del(..|.["#"]?)' "${INSTALLER_CONFIGFILE}")" || exit $?
 	# check if hwclock is set
 	if echo "${CONF_FULL}" | jq -e ".hwclock" 1>/dev/null; then
 		HWCLOCK_DEFAULT="$(echo "${CONF_FULL}" | jq -re ".hwclock")" || exit $?
@@ -53,33 +53,22 @@ echo "setting hwclock to: ${HARDWARECLOCK}" 1>&2
 sed -Ei 's#^clock="[^"]*"$#clock="'"${HARDWARECLOCK:0:5}"'"#' /etc/conf.d/hwclock || exit $?
 
 # timezone?
-# TIMEZONE="$(tzselect)" || exit $?
-# replace tzselect with a patched version
-# which does essentially the same but uses dialog/Xdialog
-# see https://github.com/Wuodan/tz/commit/5297b9ca06f79c334b9492713ce388b590e436e3
-# the sed commands make the few necessary changes
-PATCHVER=2018g
-if [[ "$(equery --quiet list --format='$version' timezone-data)" < "${PATCHVER}" ]]; then
-	PATCHVER=2018d
-fi
-cp /usr/bin/tzselect /tmp/tzselect.patched \
-	&& sed -i 's#^\t+#\t*#' /tmp/tzselect.patched \
-	&& patch --silent /tmp/tzselect.patched -i "${SHAREDIR}"/timezone-data-"${PATCHVER}"-dialog.patch \
-	|| exit $?
-TIMEZONE="$(SHOWDIALOG="${SHAREDIR}"/tzselect_dialog /tmp/tzselect.patched)" \
-	&& rm /tmp/tzselect.patched \
-	|| exit $?
-
 if [ -n "${TIMEZONE_DEFAULT}" ]; then
 	echo "Overriding timezone with value from config file!" 1>&2
 	TIMEZONE="${TIMEZONE_DEFAULT}"
+else
+  clear
+  TIMEZONE="$(tzselect)" || exit $?
 fi
 
 # this will be copied to chroot later
-if [ "${TIMEZONE}" != "" -a -e "/usr/share/zoneinfo/${TIMEZONE}" ]; then
+if [ "${TIMEZONE}" != "" ] && [ -e "/usr/share/zoneinfo/${TIMEZONE}" ]; then
 	echo "setting timezone to: ${TIMEZONE}" 1>&2
 	echo "${TIMEZONE}" > /etc/timezone
 	emerge --config sys-libs/timezone-data || exit $?
+else
+  printf "${TIMEZONE} doesn't seem to be valid, aborting.\n"
+  exit 1
 fi
 
 # display and ask to set date/time
